name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - ujson
  - numpy
  - pandas
  - pip
  - spacy=2.0.16
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pip:
      - torch==1.7.1
      - ray
      - ray[tune]
